apiVersion: v1
kind: LimitRange
metadata:
  name: memory
spec:
  limits:
  - max:
      memory: {{cookiecutter.memory_limit_max}}
    min:
      memory: {{cookiecutter.memory_limit_min}}
    type: Container