apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/quarkus-app

namePrefix: single-page-app-
commonLabels:
  app.kubernetes.io/environment: dev
  app.kubernetes.io/name: single-page-app

images:
- name: image-name
  newName: quay.io/bluesman/vote-ui
  newTag: "latest"

configMapGenerator:
- literals:
  - QUARKUS_FOOBAR=sample
  name: quarkus-app-envs
