apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: develop
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: My project description
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'