apiVersion: v1
kind: LimitRange
metadata:
  name: memory
spec:
  limits:
  - default:
      cpu: 300m
      memory: 500Mi
    defaultRequest:
      cpu: "200m"
      memory: 500Mi
    max:
      memory: 1Gi
    min:
      memory: 500Mi
    type: Container